In [1]:
import numpy as np
dir (np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [3]:
arr1 = np.array([45,26,52,25])
print(arr1)

[45 26 52 25]


In [4]:
arr1.ndim

1

In [5]:
arr1.shape

(4,)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([[47,84,56,54],[98,95,96,36],[78,96,32,32]])
print(arr2)

[[47 84 56 54]
 [98 95 96 36]
 [78 96 32 32]]


In [8]:
arr2.shape

(3, 4)

In [9]:
arr2.ndim

2

In [10]:
np.linspace(14,55)

array([14.        , 14.83673469, 15.67346939, 16.51020408, 17.34693878,
       18.18367347, 19.02040816, 19.85714286, 20.69387755, 21.53061224,
       22.36734694, 23.20408163, 24.04081633, 24.87755102, 25.71428571,
       26.55102041, 27.3877551 , 28.2244898 , 29.06122449, 29.89795918,
       30.73469388, 31.57142857, 32.40816327, 33.24489796, 34.08163265,
       34.91836735, 35.75510204, 36.59183673, 37.42857143, 38.26530612,
       39.10204082, 39.93877551, 40.7755102 , 41.6122449 , 42.44897959,
       43.28571429, 44.12244898, 44.95918367, 45.79591837, 46.63265306,
       47.46938776, 48.30612245, 49.14285714, 49.97959184, 50.81632653,
       51.65306122, 52.48979592, 53.32653061, 54.16326531, 55.        ])

In [11]:
np.linspace(14,55,20)

array([14.        , 16.15789474, 18.31578947, 20.47368421, 22.63157895,
       24.78947368, 26.94736842, 29.10526316, 31.26315789, 33.42105263,
       35.57894737, 37.73684211, 39.89473684, 42.05263158, 44.21052632,
       46.36842105, 48.52631579, 50.68421053, 52.84210526, 55.        ])

In [12]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros(12)+ 13

array([13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13.])

In [15]:
np.ones(12)*14

array([14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.])

In [16]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [19]:
np.eye(4,6)*4

array([[4., 0., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0., 0.],
       [0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.]])

In [20]:
np.eye(4,6)+5

array([[6., 5., 5., 5., 5., 5.],
       [5., 6., 5., 5., 5., 5.],
       [5., 5., 6., 5., 5., 5.],
       [5., 5., 5., 6., 5., 5.]])

In [21]:
arr3= np.arange(15,101)
print(arr3)

[ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [22]:
arr3= np.arange(15,101,3)
print(arr3)

[15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84
 87 90 93 96 99]


In [26]:
arr4 = np.random.randint(14,80)
arr4

45

In [27]:
arr4 = np.random.randint(14,80,50)
arr4

array([68, 15, 36, 76, 47, 67, 78, 69, 33, 56, 79, 50, 24, 48, 40, 69, 28,
       76, 17, 47, 63, 36, 31, 18, 21, 75, 33, 52, 58, 58, 32, 74, 38, 39,
       27, 15, 14, 25, 77, 24, 47, 45, 27, 44, 23, 56, 73, 58, 26, 14])

In [29]:
np.random.seed(1)
arr4 = np.random.randint(14,80,100)
arr4

array([51, 26, 23, 19, 78, 30, 15, 20, 39, 64, 34, 32, 25, 42, 43, 28, 64,
       27, 23, 21, 77, 75, 36, 71, 15, 14, 74, 22, 27, 61, 44, 17, 35, 63,
       71, 17, 38, 57, 40, 66, 55, 29, 78, 39, 21, 40, 39, 36, 23, 37, 41,
       51, 71, 52, 22, 46, 48, 24, 37, 29, 39, 76, 60, 46, 37, 69, 79, 17,
       14, 20, 66, 16, 35, 21, 57, 34, 44, 50, 21, 59, 71, 27, 24, 37, 21,
       38, 34, 46, 26, 79, 74, 38, 16, 24, 68, 62, 68, 29, 19, 31])

In [30]:
arr5 = arr4.reshape(10,10) ##converting one D to two D 
arr5

array([[51, 26, 23, 19, 78, 30, 15, 20, 39, 64],
       [34, 32, 25, 42, 43, 28, 64, 27, 23, 21],
       [77, 75, 36, 71, 15, 14, 74, 22, 27, 61],
       [44, 17, 35, 63, 71, 17, 38, 57, 40, 66],
       [55, 29, 78, 39, 21, 40, 39, 36, 23, 37],
       [41, 51, 71, 52, 22, 46, 48, 24, 37, 29],
       [39, 76, 60, 46, 37, 69, 79, 17, 14, 20],
       [66, 16, 35, 21, 57, 34, 44, 50, 21, 59],
       [71, 27, 24, 37, 21, 38, 34, 46, 26, 79],
       [74, 38, 16, 24, 68, 62, 68, 29, 19, 31]])

In [31]:
arr5[5,5]

46

In [33]:
arr5[4:7,3:6]

array([[39, 21, 40],
       [52, 22, 46],
       [46, 37, 69]])

In [34]:
arr5[4:7,3:6]=82 ##broadcasting
arr5

array([[51, 26, 23, 19, 78, 30, 15, 20, 39, 64],
       [34, 32, 25, 42, 43, 28, 64, 27, 23, 21],
       [77, 75, 36, 71, 15, 14, 74, 22, 27, 61],
       [44, 17, 35, 63, 71, 17, 38, 57, 40, 66],
       [55, 29, 78, 82, 82, 82, 39, 36, 23, 37],
       [41, 51, 71, 82, 82, 82, 48, 24, 37, 29],
       [39, 76, 60, 82, 82, 82, 79, 17, 14, 20],
       [66, 16, 35, 21, 57, 34, 44, 50, 21, 59],
       [71, 27, 24, 37, 21, 38, 34, 46, 26, 79],
       [74, 38, 16, 24, 68, 62, 68, 29, 19, 31]])

In [35]:
arr6 = arr5.flatten() ## converting two dimension to one dimension
arr6

array([51, 26, 23, 19, 78, 30, 15, 20, 39, 64, 34, 32, 25, 42, 43, 28, 64,
       27, 23, 21, 77, 75, 36, 71, 15, 14, 74, 22, 27, 61, 44, 17, 35, 63,
       71, 17, 38, 57, 40, 66, 55, 29, 78, 82, 82, 82, 39, 36, 23, 37, 41,
       51, 71, 82, 82, 82, 48, 24, 37, 29, 39, 76, 60, 82, 82, 82, 79, 17,
       14, 20, 66, 16, 35, 21, 57, 34, 44, 50, 21, 59, 71, 27, 24, 37, 21,
       38, 34, 46, 26, 79, 74, 38, 16, 24, 68, 62, 68, 29, 19, 31])

In [36]:
np.mean(arr6)

45.0

In [37]:
np.median(arr6)

38.5

In [38]:
np.sum(arr6)

4500

In [39]:
np.max(arr6)

82

In [40]:
np.min(arr6)

14

In [41]:
np.argmax(arr6)

43

In [42]:
np.argmin(arr6)

25

In [43]:
np.log(arr6)

array([3.93182563, 3.25809654, 3.13549422, 2.94443898, 4.35670883,
       3.40119738, 2.7080502 , 2.99573227, 3.66356165, 4.15888308,
       3.52636052, 3.4657359 , 3.21887582, 3.73766962, 3.76120012,
       3.33220451, 4.15888308, 3.29583687, 3.13549422, 3.04452244,
       4.34380542, 4.31748811, 3.58351894, 4.26267988, 2.7080502 ,
       2.63905733, 4.30406509, 3.09104245, 3.29583687, 4.11087386,
       3.78418963, 2.83321334, 3.55534806, 4.14313473, 4.26267988,
       2.83321334, 3.63758616, 4.04305127, 3.68887945, 4.18965474,
       4.00733319, 3.36729583, 4.35670883, 4.40671925, 4.40671925,
       4.40671925, 3.66356165, 3.58351894, 3.13549422, 3.61091791,
       3.71357207, 3.93182563, 4.26267988, 4.40671925, 4.40671925,
       4.40671925, 3.87120101, 3.17805383, 3.61091791, 3.36729583,
       3.66356165, 4.33073334, 4.09434456, 4.40671925, 4.40671925,
       4.40671925, 4.36944785, 2.83321334, 2.63905733, 2.99573227,
       4.18965474, 2.77258872, 3.55534806, 3.04452244, 4.04305

In [44]:
np.percentile(arr6,65)

55.70000000000002

In [45]:
np.var(arr6)

494.64

In [46]:
np.std(arr6)

22.240503591420765